const String listPageTitle = 'Users list';
const String errorPageTitle = 'Users list';
const String usersListErrorMessage = 'Error occurred while loading data...';
const String noUsersTextMessage = 'No users found';
const String usersListFilePath = 'assets/users_list.json';
const String gorestBaseUrl = 'https://gorest.co.in';
const String usersListEndpoint = '/public/v2/users';
const String clientErrorMessage = 'Client Error';
const String serverErrorMessage = 'Server Error';
const String unexpectedErrorMessage = 'Unexpected Error';
const String noInternetErrorMessage =
    'No internet connection. Please check your connection and try again.';
const String editUserDialogTitle = 'Edit User';
const String editUserDialogNameTextFieldTitle = 'Name';
const String editUserDialogEmailTextFieldTitle = 'Email';
const String editUserDialogGenderLabel = 'Gender';
const String editUserDialogStatusLabel = 'Status';
const String editUserDialogCancelButtonText = 'Cancel';
const String editUserDialogSaveAndCloseButtonText = 'Save & Close';
